CREATE TABLE IF NOT EXISTS tienda(
id_tienda VARCHAR(30) NOT NULL,
nombre VARCHAR(50) NOT NULL,
direccion VARCHAR(50) NOT NULL,
telefono_1 VARCHAR(15) NOT NULL,
telefono_2 VARCHAR(15) NULL,
email VARCHAR(30) NULL,
horario VARCHAR(50) NULL,
CONSTRAINT PK_ID_TIENDA PRIMARY KEY(id_tienda)
);

CREATE TABLE IF NOT EXISTS tiempo(
id_tiempo INT AUTO_INCREMENT NOT NULL,
tienda_1 VARCHAR(30) NOT NULL, 
tienda_2 VARCHAR(30) NOT NULL,
tiempo_pedido INT NOT NULL,
CONSTRAINT PK_ID_TIEMPO PRIMARY KEY(id_tiempo)
);

CREATE TABLE IF NOT EXISTS empleado(
id_empleado VARCHAR(30) NOT NULL,
nombre VARCHAR(50) NOT NULL,
dpi VARCHAR(20) NOT NULL,
nit VARCHAR(20) NULL,
email VARCHAR(30) NOT NULL,
direccion VARCHAR(50) NOT NULL,
telefono VARCHAR(15) NOT NULL,
CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY(id_empleado)
);

CREATE TABLE IF NOT EXISTS cliente(
id_cliente INT AUTO_INCREMENT NOT NULL,
nombre VARCHAR(50) NOT NULL,
nit VARCHAR(20) NOT NULL,
telefono VARCHAR(15) NOT NULL,
dpi VARCHAR(20) NULL,
credito DECIMAL(65,2) NULL,
email VARCHAR(30) NULL,
direccion VARCHAR(50) NULL,
CONSTRAINT PK_ID_CLIENTE PRIMARY KEY(id_cliente)
);

CREATE TABLE IF NOT EXISTS venta(
id_venta INT AUTO_INCREMENT NOT NULL,
id_tienda VARCHAR(30) NOT NULL,
id_empleado VARCHAR(30) NOT NULL,
nit VARCHAR(20) NULL,
codigo_producto VARCHAR(25) NOT NULL,
cantidad_venta INT NOT NULL,
total_a_pagar DECIMAL(65,5) NOT NULL,
pago_efectico DECIMAL(65,5) NOT NULL,
pago_credito DECIMAL(65,5) NOT NULL,
fecha_venta DATE NOT NULL,
CONSTRAINT PK_ID_VENTA PRIMARY KEY(id_venta),
CONSTRAINT FK_CODIGO_PRODUCTO FOREIGN KEY(codigo_producto)
REFERENCES producto(codigo_producto),
CONSTRAINT FK_ID_TIENDA FOREIGN KEY(id_tienda)
REFERENCES tienda(id_tienda),
CONSTRAINT FK_ID_EMPLEADO FOREIGN KEY(id_empleado)
REFERENCES empleado(id_empleado)
);

CREATE TABLE IF NOT EXISTS producto(
codigo_producto VARCHAR(25) NOT NULL, 
nombre VARCHAR(50) NOT NULL,
fabricante VARCHAR(30) NOT NULL, 
cantidad INT NOT NULL,
precio DECIMAL(65,8) NOT NULL,
descripcion VARCHAR(75) NULL,
garantia INT NULL,
CONSTRAINT PK_CODIGO_PRODUCTO PRIMARY KEY(codigo_producto)
);

CREATE TABLE IF NOT EXISTS suministra(
id_suministro INT AUTO_INCREMENT NOT NULL,
tienda VARCHAR(30) NOT NULL,
nombre_producto VARCHAR(25) NOT NULL,
producto VARCHAR(25) NOT NULL,
cantidad_tienda INT NOT NULL,
CONSTRAINT PK_ID_SUMINISTRO PRIMARY KEY(id_suministro),
CONSTRAINT FK_TIENDA FOREIGN KEY(tienda)
REFERENCES tienda(id_tienda),
CONSTRAINT FK_PRODUCTO FOREIGN KEY(producto)
REFERENCES producto(codigo_producto)
);

CREATE TABLE IF NOT EXISTS pedido(
id_pedido INT AUTO_INCREMENT NOT NULL,
nit_cliente VARCHAR(20) NOT NULL,
fecha_pedido DATE NOT NULL,
tienda_origen VARCHAR(30) NOT NULL,
tienda_destino VARCHAR(30) NOT NULL,
pedido_a_tiempo BOOLEAN NULL,
total DECIMAL(65,5) NOT NULL,
pago_anticipado DECIMAL(65,5) NULL,
CONSTRAINT PK_ID_PEDIDO PRIMARY KEY(id_pedido),
CONSTRAINT FK_TIENDA_ORIGEN FOREIGN KEY(tienda_origen)
REFERENCES tienda(id_tienda),
CONSTRAINT FK_TIENDA_DESTINO FOREIGN KEY(tienda_destino)
REFERENCES tienda(id_tienda)
);

CREATE TABLE IF NOT EXISTS contiene(
id_contiene INT AUTO_INCREMENT NOT NULL,
id_producto VARCHAR(25) NOT NULL,
id_pedido INT NOT NULL,
cantidad INT NOT NULL,
suma DECIMAL(65,5) NOT NULL,
CONSTRAINT PK_ID_CONTIENE PRIMARY KEY(id_contiene),
CONSTRAINT FK_ID_PEDIDO FOREIGN KEY(id_pedido)
REFERENCES pedido(id_pedido),
CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY(id_producto)
REFERENCES producto(codigo_producto)
);
