/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.Archivos;
import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author jara
 */
public final class JFCargarRegistro extends javax.swing.JFrame {

    Archivos a = new Archivos();
    Connection cn = ConnectionMysql.conector();

    /**
     * Creates new form JFCargarRegistro
     */
    public JFCargarRegistro() {
        super("Cargar Registros");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        initComponents();
        txtAviso.setVisible(false);
        btnNext.setVisible(false);
        consultaRegistros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnselec = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarchivos = new javax.swing.JTextArea();
        txtAviso = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("Para cargar todos los registros click en Seleccionar Documento");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 20, 390, 19);

        btnselec.setText("Seleccionar Documento");
        btnselec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecActionPerformed(evt);
            }
        });
        jPanel1.add(btnselec);
        btnselec.setBounds(100, 60, 180, 27);

        txtarchivos.setColumns(20);
        txtarchivos.setRows(5);
        jScrollPane1.setViewportView(txtarchivos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 120, 490, 260);

        txtAviso.setText("Ya existen registros! ");
        jPanel1.add(txtAviso);
        txtAviso.setBounds(310, 59, 140, 30);

        btnNext.setText("Ir a tienda");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);
        btnNext.setBounds(480, 60, 140, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnselecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecActionPerformed
        String s = a.subirTxt();
        System.out.println("Este mero es: " + s);
    }//GEN-LAST:event_btnselecActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        JFChooseStore cs = new JFChooseStore();
        cs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnselec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtAviso;
    private javax.swing.JTextArea txtarchivos;
    // End of variables declaration//GEN-END:variables

    public void consultaRegistros() {
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM tienda");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                btnselec.setEnabled(false);
                txtAviso.setVisible(true);
                System.out.println("Se encontro tienda");
            }
        } catch (SQLException e) {
            System.out.println("No se puede comprobar si hay registros! " + e);
        }
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM tiempo");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                btnselec.setEnabled(false);
                txtAviso.setVisible(true);
                System.out.println("Se encontro tiempo");
            }
        } catch (SQLException e) {
            System.out.println("No se puede comprobar si hay registros! " + e);
        }
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM cliente");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                btnselec.setEnabled(false);
                txtAviso.setVisible(true);
                System.out.println("Se encontro cliente");
            }
        } catch (SQLException e) {
            System.out.println("No se puede comprobar si hay registros! " + e);
        }
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM empleado");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                btnselec.setEnabled(false);
                txtAviso.setVisible(true);
                System.out.println("Se encontro empleado");
            }
        } catch (SQLException e) {
            System.out.println("No se puede comprobar si hay registros! " + e);
        }
        try {
            PreparedStatement ps = cn.prepareStatement("SELECT * FROM pedido");
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                btnselec.setEnabled(false);
                txtAviso.setVisible(true);
                System.out.println("Se encontro pedido");
            }
        } catch (SQLException e) {
            System.out.println("No se puede comprobar si hay registros! " + e);
        }
        if(txtAviso.isVisible()){
        btnNext.setVisible(true);
        }
    }
}
