/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jara
 */
public class JFChooseStore extends javax.swing.JFrame {

    static Connection cn = ConnectionMysql.conector();
    static PreparedStatement ps = null;
    static ResultSet rs = null;
    public static String TiendaSelect;
    ArrayList<String> tiendas = new ArrayList<String>();
    String combo;

    /**
     * Creates new form JFChooseStore
     */
    public JFChooseStore() {
        super("Seleccionando Tienda");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        initComponents();
        tiendas = obtenerTiendas();
        for (int i = 0; i < tiendas.size(); i++) {
            comboTiendas.addItem(tiendas.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboTiendas = new javax.swing.JComboBox<>();
        btnSelecTienda = new javax.swing.JButton();
        txtSelect = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Seleccione la tienda a la cual desea ingresar:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 520, 40);

        comboTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTiendasActionPerformed(evt);
            }
        });
        jPanel1.add(comboTiendas);
        comboTiendas.setBounds(90, 80, 180, 31);

        btnSelecTienda.setText("Listo");
        btnSelecTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecTiendaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecTienda);
        btnSelecTienda.setBounds(360, 160, 160, 70);
        jPanel1.add(txtSelect);
        txtSelect.setBounds(360, 80, 160, 31);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTiendasActionPerformed
        combo = comboTiendas.getSelectedItem().toString();
        txtSelect.setText(combo);
    }//GEN-LAST:event_comboTiendasActionPerformed

    private void btnSelecTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecTiendaActionPerformed
        TiendaSelect = txtSelect.getText().trim();
        JOptionPane.showMessageDialog(null, "Tienda seleccionada: " + TiendaSelect);
        JFStart j = new JFStart();
        j.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSelecTiendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecTienda;
    private javax.swing.JComboBox<String> comboTiendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSelect;
    // End of variables declaration//GEN-END:variables
    public static ArrayList<String> obtenerTiendas() {
        ArrayList<String> lista = new ArrayList<String>();
        String sql = "SELECT id_tienda FROM tienda";
        try {
            ps = cn.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                lista.add(rs.getString("id_tienda"));
            }
            JOptionPane.showMessageDialog(null, "Listado de las tiendas: " + lista);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudieron obtener las tiendas: " + e);
        }
        return lista;
    }

}
