/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jara
 */
public class JFEmployee extends javax.swing.JFrame {

    static Connection cn = ConnectionMysql.conector();
    static PreparedStatement ps = null;
    static ResultSet rs = null;
    String tienda;
    String nombreE;
    String reporteSelect;

    /**
     * Creates new form JFEmployee
     */
    public JFEmployee() {
        super("Empleado");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        setSize(900, 600);
        nombreE = JFLogin.user;
        txtEmpleado.setText(nombreE);
        tienda = JFChooseStore.TiendaSelect;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        comboReporte = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jLabel1.setText("Bienvenido: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 120, 30);

        jButton2.setText("Tienda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 70, 110, 27);

        jButton3.setText("Tiempo Entre Tiendas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(580, 70, 170, 27);

        jButton4.setText("Producos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(40, 170, 110, 27);

        jButton5.setText("Empleados");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(220, 70, 100, 27);

        jButton6.setText("Clientes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(390, 70, 100, 27);

        jButton7.setText("Venta");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(220, 170, 100, 27);

        jButton8.setText("Pedido");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(390, 170, 100, 27);

        jButton9.setText("Pedidos En Tienda");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(580, 170, 170, 27);

        comboReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        comboReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReporteActionPerformed(evt);
            }
        });
        jPanel1.add(comboReporte);
        comboReporte.setBounds(510, 330, 210, 31);

        jLabel2.setText("<html><b>1. Listado de todos los pedidos que llegarán a latienda.</b> <br>\n <b>2. Listado de pedido que están en tiempo de estar en la tienda pero debe verificarse su ingreso.</b><br>\n <b>3. Listado de todos los pedidos atrasados que llegarán a la tienda.</b><br>\n<b>4. Listado de todos los pedidos que salieron de la tienda y están en tránsito.</b><br>\n<b>5. Listado de todas las compras realizadas por un cliente.</b><br>\n<b>6. Listado de todos los pedidos en curso de un cliente.</b><br>\n<b>7. Listado de los diez productos más vendidos en un intervalo de tiempo.</b><br>\n<b>8. Listado de los productos más vendidos por tienda en un intervalo de tiempo.</b><br>\n<b>9.Listado de productos que nunca se han vendido por tienda.</b></html>");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 240, 410, 300);

        jLabel3.setText("<html><b>Seleccione el Reporte que desea ver en relacion al numero de reporte.</b></html>");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 250, 310, 60);

        jLabel4.setText("<html><b>Seleccione en los botones si desea agregar o modificar los registros.</b></html>");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 40, 490, 18);

        txtEmpleado.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        jPanel1.add(txtEmpleado);
        txtEmpleado.setBounds(210, 10, 390, 30);

        jButton1.setText("Ir a Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 450, 140, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFCreateStore cs = new JFCreateStore();
        cs.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFSale s = new JFSale();
        s.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFNewUserE e = new JFNewUserE();
        e.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFNewUserC c = new JFNewUserC();
        c.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFOrder o = new JFOrder();
        o.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JFOrderInStore ois = new JFOrderInStore();
        ois.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void comboReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReporteActionPerformed
        reporteSelect = comboReporte.getSelectedItem().toString();
    }//GEN-LAST:event_comboReporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Cosa seleccionada: " + reporteSelect);
        generarReporte();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFTiempoEntreTiendas tet = new JFTiempoEntreTiendas();
        tet.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFCreateProduct p = new JFCreateProduct();
        p.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtEmpleado;
    // End of variables declaration//GEN-END:variables
    public void generarReporte() {
        switch (reporteSelect) {
            case "1":
                JFOrderInCome oc = new JFOrderInCome();
                oc.setVisible(true);
                break;
            case "2":
                JFOrderInComeOnTime ot = new JFOrderInComeOnTime();
                ot.setVisible(true);
                break;
            case "3":
                JFBackOrders bo = new JFBackOrders();
                bo.setVisible(true);
                break;
            case "4":
                JFOrderSent os = new JFOrderSent();
                os.setVisible(true);
                break;
            case "5":
                JFShoppingCostumer sc= new JFShoppingCostumer();
                sc.setVisible(true);
                break;
            case "6":
                JFOrdersCostumer soc = new JFOrdersCostumer();
                soc.setVisible(true);
                break;
            case "7":
                JFMostSellP msp = new JFMostSellP();
                msp.setVisible(true);
                break;
            case "8":
                break;
            case "9":
                break;
            default:
                System.out.println("No se puede mano");
                break;
        }
    }
}
