/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jara
 */
public class JFLogin extends javax.swing.JFrame {

    static Connection cn = ConnectionMysql.conector();
    static PreparedStatement ps = null;
    static ResultSet rs = null;
    int usuario;
    public static String user;
    String lblUser;

    /**
     * Creates new form JFNewUserC
     */
    public JFLogin() {
        super("Inicio de Sesión");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        usuario = JFStart.login;
        initComponents();
        JOptionPane.showMessageDialog(null, "Usuario: " + usuario);
        mostrarInfo();
        txtAviso.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAviso = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        txtAviso.setText("Debes ingresar los campos requeridos.");
        txtAviso.setToolTipText("");
        jPanel1.add(txtAviso);
        txtAviso.setBounds(160, 320, 250, 20);

        txtEmpleado.setText("Ingrese su ID de Empleado");
        jPanel1.add(txtEmpleado);
        txtEmpleado.setBounds(200, 110, 180, 19);
        jPanel1.add(txtDato);
        txtDato.setBounds(200, 150, 160, 31);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar);
        btnIngresar.setBounds(230, 250, 100, 50);

        jLabel4.setText("Para ingresar debe de llenar los campos correspondientes");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 30, 440, 30);

        txtCliente.setText("Ingrese su NIT");
        jPanel1.add(txtCliente);
        txtCliente.setBounds(220, 110, 110, 19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (txtDato.getText().isEmpty()) {
            txtAviso.setVisible(true);
        } else {
            lblUser = txtDato.getText();
            String sql = "SELECT nombre FROM empleado WHERE id_empleado=?";
            try {
                ps = cn.prepareStatement(sql);
                ps.setString(1, lblUser);
                rs = ps.executeQuery();
                if (rs.next()) {
                    user = rs.getString("nombre");
                    JFEmployee e = new JFEmployee();
                    e.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Entre en empleado");
                } else {
                    user = "";
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en el Login, revise sus datos!");
            }

            String sql1 = "SELECT nombre FROM cliente WHERE nit=?";
            try {
                ps = cn.prepareStatement(sql1);
                ps.setString(1, lblUser);
                rs = ps.executeQuery();
                if (rs.next()) {
                    user = rs.getString("nombre");
                    JFCostumer c = new JFCostumer();
                    c.setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(null, "Entre en cliente");
                } else {
                    user = "";
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error en el Login, revise sus datos!");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAviso;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JTextField txtDato;
    private javax.swing.JLabel txtEmpleado;
    // End of variables declaration//GEN-END:variables
    public void mostrarInfo() {
        if (usuario == 0) {
            txtEmpleado.setVisible(true);
            txtCliente.setVisible(false);
        } else if (usuario == 1) {
            txtEmpleado.setVisible(false);
            txtCliente.setVisible(true);
        }
    }
}
