/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jara
 */
public class JFOrderInStore extends javax.swing.JFrame {

    static Connection cn = ConnectionMysql.conector();
    static PreparedStatement ps = null;
    static ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    String tienda;

    /**
     * Creates new form JFOrderInStore
     */
    public JFOrderInStore() {
        super("Ver pedidos de la Tienda");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        setSize(900, 500);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tienda = JFChooseStore.TiendaSelect;
        listarPedidosEnTienda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPedidos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 430, 350);

        jLabel1.setText("Para verificar el pedido click sobre el registro que desea ver.");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 400, 19);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(490, 100, 180, 31);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(490, 170, 180, 31);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(490, 240, 180, 31);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(490, 310, 180, 31);

        jLabel2.setText("ID Pedido");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 80, 150, 19);

        jLabel3.setText("Fecha de Pedido");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 150, 170, 19);

        jLabel4.setText("Tienda Origen");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 220, 170, 19);

        jLabel5.setText("Tienda Destino");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(490, 290, 180, 19);

        jButton1.setText("Actualizar pedido");
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 380, 220, 27);

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(720, 170, 190, 31);

        jLabel6.setText("Pedido A tiempo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(720, 150, 130, 19);

        jLabel7.setText("Registrar Pedido en tienda");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(720, 220, 180, 19);

        jCheckBox1.setText("Recibir en tienda");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(720, 250, 150, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPedidosMouseClicked

    }//GEN-LAST:event_tablaPedidosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
private void listarPedidosEnTienda() {
        String sql = "SELECT id_pedido, nit_cliente, fecha_pedido, tienda_origen, tienda_destino FROM pedido WHERE tienda_destino=?";
        model.setColumnIdentifiers(new Object[]{"ID Pedido", "NIT", "Fecha", "Origen", "Destino"});
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, tienda);
            rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id_pedido"), rs.getString("nit_cliente"), rs.getString("fecha_pedido"), rs.getString("tienda_origen"), rs.getString("tienda_destino")});
            }
            tablaPedidos.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error al ingresar datos a la tabla: " + e);
        }

    }

    public void limpiarLista() {
        model = (DefaultTableModel) tablaPedidos.getModel();
        int a = tablaPedidos.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            model.removeRow(model.getRowCount() - 1);
        }
    }
}
