/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jara
 */
public class JFOrderInCome extends javax.swing.JFrame {

    Connection cn = ConnectionMysql.conector();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel model = new DefaultTableModel();
    String tienda;

    /**
     * Creates new form JFOrderInCome
     */
    public JFOrderInCome() {
        super("Pedidos por llegar");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tienda = JFChooseStore.TiendaSelect;
        listarOC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOC = new javax.swing.JTable();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        tablaOC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaOC);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 650, 370);

        btnExportar.setText("Exportar HTML");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar);
        btnExportar.setBounds(230, 410, 190, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        try {
            generar(model);
        } catch (IOException ex) {
            Logger.getLogger(JFOrderInCome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaOC;
    // End of variables declaration//GEN-END:variables

    private void listarOC() {
        String sql = "SELECT * FROM pedido WHERE en_tienda=0 AND tienda_destino=?";
        model.setColumnIdentifiers(new Object[]{"ID Pedido", "Fecha", "NIT Cliente"});
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, tienda);
            rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("id_pedido"), rs.getString("fecha_pedido"), rs.getString("nit_cliente")});
            }
            tablaOC.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error al ingresar datos a la tabla: " + e);
        }
    }

    public void generar(DefaultTableModel model) throws IOException {
        FileWriter fichero = new FileWriter("/home/jara/NetBeansProjects/IntelafIPC2/Reporte.html");
        fichero.write("<!DOCTYPE HTML5>");
        fichero.write(" <html>");
        fichero.write("<head>");
        fichero.write("<title>Reportes</title>");
        fichero.write("<meta charset='utf-8'>");       
        fichero.write("</head>");
        fichero.write("<body>");
        fichero.write("<h2>Listado de todos los pedidos que llegarán a la tienda.</h2>");
        fichero.write("<table border='1'>");
        fichero.write("<tr>\n"
                + "\n"
                + "    <th>ID Pedido</th>\n"
                + "\n"
                + "    <th>Fecha</th>\n"
                + "\n"
                + "    <th>NIT Cliente</th>\n"
                + "\n"
                + "  </tr>\n");

        for (int i = 0; i < 10; i++) {
        }
        int filas = tablaOC.getRowCount();
        for (int i = 0; i < filas; i++) {
            fichero.write("<tr>");
            int columnas = tablaOC.getColumnCount();
            for (int j = 0; j < columnas; j++) {
                fichero.write("<th>" + tablaOC.getValueAt(i, j) + "</th>");
            }
            fichero.write("</tr>");
        }
        fichero.write("</table>");
        fichero.write("</body>");
        fichero.write("</html>");
        fichero.close();
    }
}
