/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.intelaf.UI;

import com.mycompany.intelaf.Backend.ConnectionMysql;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jara
 */
public class JFShoppingCostumer extends javax.swing.JFrame {

    Connection cn = ConnectionMysql.conector();
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel model = new DefaultTableModel();
    String nit;

    /**
     * Creates new form JFShoppingCostumer
     */
    public JFShoppingCostumer() {
        super("Compras realizadas por un cliente");
        this.setIconImage(new ImageIcon(getClass().getResource("/Images/logointelaf.png")).getImage());
        initComponents();
        setSize(900, 550);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSC = new javax.swing.JTable();
        btnEx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCc = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 81, 0));
        jPanel1.setLayout(null);

        tableSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableSC);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 50, 790, 360);

        btnEx.setText("Exportar HTML");
        btnEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExActionPerformed(evt);
            }
        });
        jPanel1.add(btnEx);
        btnEx.setBounds(340, 430, 220, 30);

        jLabel1.setText("Ingrese el NIT del cliente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 9, 180, 30);
        jPanel1.add(txtCc);
        txtCc.setBounds(370, 10, 260, 31);

        jCheckBox1.setText("Ver Listado");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(640, 11, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExActionPerformed
        try {
            generar(model);
        } catch (IOException ex) {
            Logger.getLogger(JFOrderInCome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (txtCc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el NIT del cliente!");
        } else {
            nit = txtCc.getText();
            limpiarLista();
            listarCC();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEx;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSC;
    private javax.swing.JTextField txtCc;
    // End of variables declaration//GEN-END:variables
    public void listarCC() {
        String sql = "select * from venta where nit=?";
        model.setColumnIdentifiers(new Object[]{"ID Compra", "NIT Cliente", "Producto", "Cantidad", "Pago", "Fecha"});
        try {
            ps = cn.prepareStatement(sql);
            ps.setString(1, nit);
            rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("id_venta"), rs.getString("nit"), rs.getString("codigo_producto"), rs.getInt("cantidad_venta"), rs.getDouble("total_a_pagar"), rs.getDate("fecha_venta")});
            }
            tableSC.setModel(model);
        } catch (SQLException e) {
            System.out.println("Error al ingresar datos a la tabla: " + e);
        }
    }

    public void limpiarLista() {
        model = (DefaultTableModel) tableSC.getModel();
        int a = tableSC.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            model.removeRow(model.getRowCount() - 1);
        }
    }

    public void generar(DefaultTableModel model) throws IOException {
        FileWriter fichero = new FileWriter("/home/jara/NetBeansProjects/IntelafIPC2/Reporte.html");
        fichero.write("<!DOCTYPE HTML5>");
        fichero.write(" <html>");
        fichero.write("<head>");
        fichero.write("<title>Reportes</title>");
        fichero.write("<meta charset='utf-8'>");
        fichero.write("</head>");
        fichero.write("<body>");
        fichero.write("<h2>Listado de todas las compras realizadas por un cliente.</h2>");
        fichero.write("<table border='1'>");
        fichero.write("<tr>\n"
                + "\n"
                + "    <th>ID Compra</th>\n"
                + "\n"
                + "    <th>NIT Cliente</th>\n"
                + "\n"
                + "    <th>Producto</th>\n"
                + "\n"
                + "    <th>Cantidad</th>\n"
                + "\n"
                + "    <th>Pago</th>\n"
                + "\n"
                + "    <th>Fecha</th>\n"
                + "\n"
                + "  </tr>\n");
        for (int i = 0; i < 10; i++) {
        }
        int filas = tableSC.getRowCount();
        for (int i = 0; i < filas; i++) {
            fichero.write("<tr>");
            int columnas = tableSC.getColumnCount();
            for (int j = 0; j < columnas; j++) {
                fichero.write("<th>" + tableSC.getValueAt(i, j) + "</th>");
            }
            fichero.write("</tr>");
        }
        fichero.write("</table>");
        fichero.write("</body>");
        fichero.write("</html>");
        fichero.close();
    }
}
